In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [5]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[ 0.3223,  0.3329,  0.0274],
         [ 0.8869,  0.2897,  0.2971],
         [ 0.6580,  0.6499,  0.1755]],

        [[ 0.6014,  0.4176,  0.4459],
         [ 0.3411,  0.5053,  0.6439],
         [ 0.5025,  0.5773,  0.8026]],

        [[ 0.4163,  0.2840,  0.2118],
         [ 0.4380,  0.6860,  0.0177],
         [ 0.9622,  0.3538,  0.2637]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [9]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [11]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(1.2254)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 0.9748,  1.0362,  1.4685,  1.5067,  1.1946],
        [ 0.4755,  0.6496,  0.7102,  0.8827,  0.6346],
        [ 0.9822,  1.2242,  1.5950,  1.7656,  1.2309],
        [ 0.8757,  0.8744,  1.6154,  1.7314,  0.7647],
        [ 1.0214,  1.4330,  1.7170,  1.9373,  1.5229]])